/*
 * Messente API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.messente.api;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ErrorTitlePhonebook
 */
public class ErrorTitlePhonebookTest {
    /**
     * Model tests for ErrorTitlePhonebook
     */
    @Test
    public void testErrorTitlePhonebook() {
        // TODO: test ErrorTitlePhonebook
    }

}
