/*
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.messente.api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.messente.api.OmnimessageMessagesInner;
import com.messente.api.Priority;
import com.messente.api.TextStore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.messente.JSON;

/**
 * An omnimessage
 */
@ApiModel(description = "An omnimessage")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Omnimessage {
  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  private String to;

  public static final String SERIALIZED_NAME_MESSAGES = "messages";
  @SerializedName(SERIALIZED_NAME_MESSAGES)
  private List<OmnimessageMessagesInner> messages = new ArrayList<>();

  public static final String SERIALIZED_NAME_DLR_URL = "dlr_url";
  @SerializedName(SERIALIZED_NAME_DLR_URL)
  private String dlrUrl;

  public static final String SERIALIZED_NAME_TEXT_STORE = "text_store";
  @SerializedName(SERIALIZED_NAME_TEXT_STORE)
  private TextStore textStore;

  public static final String SERIALIZED_NAME_TIME_TO_SEND = "time_to_send";
  @SerializedName(SERIALIZED_NAME_TIME_TO_SEND)
  private OffsetDateTime timeToSend;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Priority priority;

  public Omnimessage() { 
  }

  public Omnimessage to(String to) {
    
    this.to = to;
    return this;
  }

   /**
   * Phone number in e.164 format
   * @return to
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Phone number in e.164 format")

  public String getTo() {
    return to;
  }


  public void setTo(String to) {
    this.to = to;
  }


  public Omnimessage messages(List<OmnimessageMessagesInner> messages) {
    
    this.messages = messages;
    return this;
  }

  public Omnimessage addMessagesItem(OmnimessageMessagesInner messagesItem) {
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * An array of messages
   * @return messages
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "An array of messages")

  public List<OmnimessageMessagesInner> getMessages() {
    return messages;
  }


  public void setMessages(List<OmnimessageMessagesInner> messages) {
    this.messages = messages;
  }


  public Omnimessage dlrUrl(String dlrUrl) {
    
    this.dlrUrl = dlrUrl;
    return this;
  }

   /**
   * URL where the delivery report will be sent
   * @return dlrUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL where the delivery report will be sent")

  public String getDlrUrl() {
    return dlrUrl;
  }


  public void setDlrUrl(String dlrUrl) {
    this.dlrUrl = dlrUrl;
  }


  public Omnimessage textStore(TextStore textStore) {
    
    this.textStore = textStore;
    return this;
  }

   /**
   * Get textStore
   * @return textStore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TextStore getTextStore() {
    return textStore;
  }


  public void setTextStore(TextStore textStore) {
    this.textStore = textStore;
  }


  public Omnimessage timeToSend(OffsetDateTime timeToSend) {
    
    this.timeToSend = timeToSend;
    return this;
  }

   /**
   * Optional parameter for sending messages at some specific time in the future.   Time must be specified in the ISO-8601 format.   If no timezone is specified, then the timezone is assumed to be UTC    Examples:    * Time specified with timezone: 2018-06-22T09:05:07+00:00 Time specified in UTC: 2018-06-22T09:05:07Z   * Time specified without timezone: 2018-06-22T09:05 (equivalent to 2018-06-22T09:05+00:00)
   * @return timeToSend
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional parameter for sending messages at some specific time in the future.   Time must be specified in the ISO-8601 format.   If no timezone is specified, then the timezone is assumed to be UTC    Examples:    * Time specified with timezone: 2018-06-22T09:05:07+00:00 Time specified in UTC: 2018-06-22T09:05:07Z   * Time specified without timezone: 2018-06-22T09:05 (equivalent to 2018-06-22T09:05+00:00)")

  public OffsetDateTime getTimeToSend() {
    return timeToSend;
  }


  public void setTimeToSend(OffsetDateTime timeToSend) {
    this.timeToSend = timeToSend;
  }


  public Omnimessage priority(Priority priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Priority getPriority() {
    return priority;
  }


  public void setPriority(Priority priority) {
    this.priority = priority;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Omnimessage omnimessage = (Omnimessage) o;
    return Objects.equals(this.to, omnimessage.to) &&
        Objects.equals(this.messages, omnimessage.messages) &&
        Objects.equals(this.dlrUrl, omnimessage.dlrUrl) &&
        Objects.equals(this.textStore, omnimessage.textStore) &&
        Objects.equals(this.timeToSend, omnimessage.timeToSend) &&
        Objects.equals(this.priority, omnimessage.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, messages, dlrUrl, textStore, timeToSend, priority);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Omnimessage {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    dlrUrl: ").append(toIndentedString(dlrUrl)).append("\n");
    sb.append("    textStore: ").append(toIndentedString(textStore)).append("\n");
    sb.append("    timeToSend: ").append(toIndentedString(timeToSend)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("to");
    openapiFields.add("messages");
    openapiFields.add("dlr_url");
    openapiFields.add("text_store");
    openapiFields.add("time_to_send");
    openapiFields.add("priority");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("to");
    openapiRequiredFields.add("messages");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Omnimessage
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (Omnimessage.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in Omnimessage is not found in the empty JSON string", Omnimessage.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Omnimessage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Omnimessage` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Omnimessage.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("to") != null && !jsonObj.get("to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to").toString()));
      }
      JsonArray jsonArraymessages = jsonObj.getAsJsonArray("messages");
      if (jsonArraymessages != null) {
        // ensure the json data is an array
        if (!jsonObj.get("messages").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `messages` to be an array in the JSON string but got `%s`", jsonObj.get("messages").toString()));
        }

        // validate the optional field `messages` (array)
        for (int i = 0; i < jsonArraymessages.size(); i++) {
          OmnimessageMessagesInner.validateJsonObject(jsonArraymessages.get(i).getAsJsonObject());
        };
      }
      if (jsonObj.get("dlr_url") != null && !jsonObj.get("dlr_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dlr_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dlr_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Omnimessage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Omnimessage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Omnimessage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Omnimessage.class));

       return (TypeAdapter<T>) new TypeAdapter<Omnimessage>() {
           @Override
           public void write(JsonWriter out, Omnimessage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Omnimessage read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Omnimessage given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Omnimessage
  * @throws IOException if the JSON string is invalid with respect to Omnimessage
  */
  public static Omnimessage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Omnimessage.class);
  }

 /**
  * Convert an instance of Omnimessage to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

