/*
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.messente.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.messente.api.RcsCardContent;
import com.messente.api.RcsCardWidth;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.messente.JSON;

/**
 * RCS Carousel Card.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class RcsCarouselCard {
  public static final String SERIALIZED_NAME_CARD_WIDTH = "card_width";
  @SerializedName(SERIALIZED_NAME_CARD_WIDTH)
  @javax.annotation.Nonnull
  private RcsCardWidth cardWidth;

  public static final String SERIALIZED_NAME_CARD_CONTENTS = "card_contents";
  @SerializedName(SERIALIZED_NAME_CARD_CONTENTS)
  @javax.annotation.Nonnull
  private List<RcsCardContent> cardContents = new ArrayList<>();

  public RcsCarouselCard() {
  }

  public RcsCarouselCard cardWidth(@javax.annotation.Nonnull RcsCardWidth cardWidth) {
    this.cardWidth = cardWidth;
    return this;
  }

  /**
   * Get cardWidth
   * @return cardWidth
   */
  @javax.annotation.Nonnull
  public RcsCardWidth getCardWidth() {
    return cardWidth;
  }

  public void setCardWidth(@javax.annotation.Nonnull RcsCardWidth cardWidth) {
    this.cardWidth = cardWidth;
  }


  public RcsCarouselCard cardContents(@javax.annotation.Nonnull List<RcsCardContent> cardContents) {
    this.cardContents = cardContents;
    return this;
  }

  public RcsCarouselCard addCardContentsItem(RcsCardContent cardContentsItem) {
    if (this.cardContents == null) {
      this.cardContents = new ArrayList<>();
    }
    this.cardContents.add(cardContentsItem);
    return this;
  }

  /**
   * The contents of the carousel card.
   * @return cardContents
   */
  @javax.annotation.Nonnull
  public List<RcsCardContent> getCardContents() {
    return cardContents;
  }

  public void setCardContents(@javax.annotation.Nonnull List<RcsCardContent> cardContents) {
    this.cardContents = cardContents;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RcsCarouselCard instance itself
   */
  public RcsCarouselCard putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RcsCarouselCard rcsCarouselCard = (RcsCarouselCard) o;
    return Objects.equals(this.cardWidth, rcsCarouselCard.cardWidth) &&
        Objects.equals(this.cardContents, rcsCarouselCard.cardContents)&&
        Objects.equals(this.additionalProperties, rcsCarouselCard.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardWidth, cardContents, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RcsCarouselCard {\n");
    sb.append("    cardWidth: ").append(toIndentedString(cardWidth)).append("\n");
    sb.append("    cardContents: ").append(toIndentedString(cardContents)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("card_width");
    openapiFields.add("card_contents");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("card_width");
    openapiRequiredFields.add("card_contents");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RcsCarouselCard
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RcsCarouselCard.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RcsCarouselCard is not found in the empty JSON string", RcsCarouselCard.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RcsCarouselCard.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `card_width`
      RcsCardWidth.validateJsonElement(jsonObj.get("card_width"));
      // ensure the json data is an array
      if (!jsonObj.get("card_contents").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `card_contents` to be an array in the JSON string but got `%s`", jsonObj.get("card_contents").toString()));
      }

      JsonArray jsonArraycardContents = jsonObj.getAsJsonArray("card_contents");
      // validate the required field `card_contents` (array)
      for (int i = 0; i < jsonArraycardContents.size(); i++) {
        RcsCardContent.validateJsonElement(jsonArraycardContents.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RcsCarouselCard.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RcsCarouselCard' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RcsCarouselCard> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RcsCarouselCard.class));

       return (TypeAdapter<T>) new TypeAdapter<RcsCarouselCard>() {
           @Override
           public void write(JsonWriter out, RcsCarouselCard value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RcsCarouselCard read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             RcsCarouselCard instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RcsCarouselCard given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RcsCarouselCard
   * @throws IOException if the JSON string is invalid with respect to RcsCarouselCard
   */
  public static RcsCarouselCard fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RcsCarouselCard.class);
  }

  /**
   * Convert an instance of RcsCarouselCard to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

