/*
 * Messente API
 * [Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: messente@messente.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.messente.api;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.messente.api.RcsCardContent;
import com.messente.api.RcsCardOrientation;
import com.messente.api.RcsImageAlignment;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.messente.JSON;

/**
 * RCS standalone card object.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class RcsStandaloneCard {
  public static final String SERIALIZED_NAME_CARD_ORIENTATION = "card_orientation";
  @SerializedName(SERIALIZED_NAME_CARD_ORIENTATION)
  @javax.annotation.Nonnull
  private RcsCardOrientation cardOrientation;

  public static final String SERIALIZED_NAME_THUMBNAIL_IMAGE_ALIGNMENT = "thumbnail_image_alignment";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL_IMAGE_ALIGNMENT)
  @javax.annotation.Nonnull
  private RcsImageAlignment thumbnailImageAlignment;

  public static final String SERIALIZED_NAME_CARD_CONTENT = "card_content";
  @SerializedName(SERIALIZED_NAME_CARD_CONTENT)
  @javax.annotation.Nonnull
  private RcsCardContent cardContent;

  public RcsStandaloneCard() {
  }

  public RcsStandaloneCard cardOrientation(@javax.annotation.Nonnull RcsCardOrientation cardOrientation) {
    this.cardOrientation = cardOrientation;
    return this;
  }

  /**
   * Get cardOrientation
   * @return cardOrientation
   */
  @javax.annotation.Nonnull
  public RcsCardOrientation getCardOrientation() {
    return cardOrientation;
  }

  public void setCardOrientation(@javax.annotation.Nonnull RcsCardOrientation cardOrientation) {
    this.cardOrientation = cardOrientation;
  }


  public RcsStandaloneCard thumbnailImageAlignment(@javax.annotation.Nonnull RcsImageAlignment thumbnailImageAlignment) {
    this.thumbnailImageAlignment = thumbnailImageAlignment;
    return this;
  }

  /**
   * Get thumbnailImageAlignment
   * @return thumbnailImageAlignment
   */
  @javax.annotation.Nonnull
  public RcsImageAlignment getThumbnailImageAlignment() {
    return thumbnailImageAlignment;
  }

  public void setThumbnailImageAlignment(@javax.annotation.Nonnull RcsImageAlignment thumbnailImageAlignment) {
    this.thumbnailImageAlignment = thumbnailImageAlignment;
  }


  public RcsStandaloneCard cardContent(@javax.annotation.Nonnull RcsCardContent cardContent) {
    this.cardContent = cardContent;
    return this;
  }

  /**
   * Get cardContent
   * @return cardContent
   */
  @javax.annotation.Nonnull
  public RcsCardContent getCardContent() {
    return cardContent;
  }

  public void setCardContent(@javax.annotation.Nonnull RcsCardContent cardContent) {
    this.cardContent = cardContent;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RcsStandaloneCard instance itself
   */
  public RcsStandaloneCard putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RcsStandaloneCard rcsStandaloneCard = (RcsStandaloneCard) o;
    return Objects.equals(this.cardOrientation, rcsStandaloneCard.cardOrientation) &&
        Objects.equals(this.thumbnailImageAlignment, rcsStandaloneCard.thumbnailImageAlignment) &&
        Objects.equals(this.cardContent, rcsStandaloneCard.cardContent)&&
        Objects.equals(this.additionalProperties, rcsStandaloneCard.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardOrientation, thumbnailImageAlignment, cardContent, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RcsStandaloneCard {\n");
    sb.append("    cardOrientation: ").append(toIndentedString(cardOrientation)).append("\n");
    sb.append("    thumbnailImageAlignment: ").append(toIndentedString(thumbnailImageAlignment)).append("\n");
    sb.append("    cardContent: ").append(toIndentedString(cardContent)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("card_orientation");
    openapiFields.add("thumbnail_image_alignment");
    openapiFields.add("card_content");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("card_orientation");
    openapiRequiredFields.add("thumbnail_image_alignment");
    openapiRequiredFields.add("card_content");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RcsStandaloneCard
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RcsStandaloneCard.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RcsStandaloneCard is not found in the empty JSON string", RcsStandaloneCard.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RcsStandaloneCard.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `card_orientation`
      RcsCardOrientation.validateJsonElement(jsonObj.get("card_orientation"));
      // validate the required field `thumbnail_image_alignment`
      RcsImageAlignment.validateJsonElement(jsonObj.get("thumbnail_image_alignment"));
      // validate the required field `card_content`
      RcsCardContent.validateJsonElement(jsonObj.get("card_content"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RcsStandaloneCard.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RcsStandaloneCard' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RcsStandaloneCard> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RcsStandaloneCard.class));

       return (TypeAdapter<T>) new TypeAdapter<RcsStandaloneCard>() {
           @Override
           public void write(JsonWriter out, RcsStandaloneCard value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RcsStandaloneCard read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             RcsStandaloneCard instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RcsStandaloneCard given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RcsStandaloneCard
   * @throws IOException if the JSON string is invalid with respect to RcsStandaloneCard
   */
  public static RcsStandaloneCard fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RcsStandaloneCard.class);
  }

  /**
   * Convert an instance of RcsStandaloneCard to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

