name: Publish package to the Maven Central Repository

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish Artifacts
        env:
            ORG_GRADLE_PROJECT_mavenCentralUsername: $
            ORG_GRADLE_PROJECT_mavenCentralPassword: $
            ORG_GRADLE_PROJECT_signingInMemoryKey: $
            ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: $
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache --no-daemon

on:
  push:
    tags:
      - *
